# Use an official lightweight Python image as the base image
FROM python:3.9-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container at /app
COPY hello.py .

# Command to run the Python script when the container starts
CMD ["python", "hello.py"]
